apiVersion: v1
kind: Service
metadata:
  name: {{ include "altinity-test.fullname" . }}
  labels:
    {{- include "altinity-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-{{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "altinity-test.selectorLabels" . | nindent 4 }}
